
---
version: '2'
services:
  texts:
    container_name: texts
    restart: always
    build: https://github.com/NathanKalt/texttest.git
#      dockerfile: Dockerfile
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '3'
    network_mode: host
    command: "python app/routes.py"


